// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKg7HvcW5lb7kFacL5OVrbd_N1TdCUFQ',
    appId: '1:979143510670:web:e843cc45585461a355d7df',
    messagingSenderId: '979143510670',
    projectId: 'chat-app-001-9c4dc',
    authDomain: 'chat-app-001-9c4dc.firebaseapp.com',
    storageBucket: 'chat-app-001-9c4dc.appspot.com',
    measurementId: 'G-Q2RVYYEMJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPdfylw-39DTBcM1R3csMSiZcNXpefXTY',
    appId: '1:979143510670:android:edc0172da38a36be55d7df',
    messagingSenderId: '979143510670',
    projectId: 'chat-app-001-9c4dc',
    storageBucket: 'chat-app-001-9c4dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9wc26LvgiYfQz9jHcU_4dbRk5w87gQPI',
    appId: '1:979143510670:ios:df383d3cfc681f1f55d7df',
    messagingSenderId: '979143510670',
    projectId: 'chat-app-001-9c4dc',
    storageBucket: 'chat-app-001-9c4dc.appspot.com',
    iosClientId: '979143510670-rq9eucd2u2oktv2em66hpqep1qipg39p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
